export default {
    LIST_SHOW: 'LIST_SHOW',
    LIST_HIDE: 'LIST_HIDE',
    LIST_REFRESH: 'LIST_REFRESH',

    EDITOR_SET_HEADER: 'EDITOR_SET_HEADER',
    EDITOR_SET_CONTENT: 'EDITOR_SET_CONTENT',
    EDITOR_SET_CURRENT: 'EDITOR_SET_CURRENT',

    UTIL_SHOW_TIP: 'UTIL_SHOW_TIP',

    MODAL_SHOW: 'MODAL_SHOW',

    MENU_CHNAGE_FOCUS_MODE: 'MENU_CHNAGE_FOCUS_MODE'
}
