export default {
    SHOW_LIST: 'SHOW_LIST',
    HIDE_LIST: 'HIDE_LIST',
    SHOW_LOADING: 'SHOW_LOADING',
    REFRESH_LIST: 'REFRESH_LIST',

    SET_HEADER: 'SET_HEADER',
    SET_CONTENT: 'SET_CONTENT',
    SET_CURRENT: 'SET_CURRENT',

    SAVE_CONTENT: 'SAVE_CONTENT',

    SHOW_TIP: 'SHOW_TIP',

    SHOW_MODAL: 'SHOW_MODAL',
    CREATE_ARTICLE: 'CREATE_ARTICLE'
}
