site:
    title: "Me"
    subtitle: "Example"
    limit: 10
    theme: ./theme
    lang: tr-TR
    url: "https://github.com/jpglord/blog"
    comment: this is a comment
    logo: "-/images/avatar.png"
    config:
    # link: "{category}/{year}/{month}/{day}/{title}.html"
    # link: "{year}{month}{day}{hour}{minute}{second}.html"
    # root: "/blog"

authors:
    me:
        name: "example"
        intro: "Journalist of computer science"
        avatar: "-/images/avatar.png"

build:
    # output: "public"
    port: 8000
    # These files are copied to the public folder when 'ink build' is used
    copy:
        - "./theme/source/"
        - "./source/images/"
    # Executed commands when 'ink publish' is used
    publish: |
        git add . -A
        git commit -m "update"
        git push origin
