name: Build artifacts & Release

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name for release"
        required: false
        default: nightly
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "stable"
      - name: Build
        run: sh ./release.sh
      - if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.tag_name == 'nightly')
        name: Release Nightly
        uses: softprops/action-gh-release@v1
        with:
          files: release/ink*
          prerelease: true
          tag_name: nightly
          name: Nightly build
          generate_release_notes: true
          fail_on_unmatched_files: true
      - if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/ink*
          prerelease: false
          name: Release ${{ github.ref }}
          generate_release_notes: true
          fail_on_unmatched_files: true
